# Pre-commit hooks configuration for Yuho v3.0
# See https://pre-commit.com for more information

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(archive|sandbox|yuho_v1|yuho_v2)/
      - id: end-of-file-fixer
        exclude: ^(archive|sandbox|yuho_v1|yuho_v2)/
      - id: check-yaml
        exclude: ^(archive|sandbox|yuho_v1|yuho_v2)/
      - id: check-json
        exclude: ^(archive|sandbox|yuho_v1|yuho_v2)/
      - id: check-toml
        exclude: ^(archive|sandbox|yuho_v1|yuho_v2)/
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Python code formatting with Black
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
        exclude: ^(archive|sandbox|yuho_v1|yuho_v2)/

  # Import sorting with isort
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        exclude: ^(archive|sandbox|yuho_v1|yuho_v2)/

  # Linting with flake8
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        exclude: ^(archive|sandbox|yuho_v1|yuho_v2)/
        additional_dependencies: [
          'flake8-bugbear',
          'flake8-comprehensions',
          'flake8-simplify',
        ]

  # Type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        exclude: ^(archive|sandbox|yuho_v1|yuho_v2|yuho_v3/tests)/
        additional_dependencies: [types-all]

  # Security linting with bandit
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml']
        exclude: ^(archive|sandbox|yuho_v1|yuho_v2|yuho_v3/tests)/
        additional_dependencies: ['bandit[toml]']

  # Check for common security issues
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
      - id: python-safety-dependencies-check
        files: requirements.*\.txt$

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: ['--fix']
        exclude: ^(archive|sandbox|yuho_v1|yuho_v2)/

# Global exclusions
exclude: |
  (?x)^(
      archive/.*|
      sandbox/.*|
      yuho_v1/.*|
      yuho_v2/.*|
      .*\.egg-info/.*|
      build/.*|
      dist/.*
  )$

