#!/usr/bin/env python3
"""Emit stats.tex from coverage.json.

Reads totals from library/penal_code/_coverage/coverage.json and emits
\\newcommand definitions used by main.tex's IfFileExists fallback chain.

Usage: python3 gen_stats.py <coverage.json>
"""

import json
import sys
from pathlib import Path


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: gen_stats.py <coverage.json>", file=sys.stderr)
        return 2
    cov = json.loads(Path(argv[1]).read_text(encoding="utf-8"))
    totals = cov.get("totals", {})
    raw = totals.get("raw_sections", 0)
    enc = totals.get("encoded", raw)
    l1 = totals.get("L1_pass", 0)
    l2 = totals.get("L2_pass", 0)
    l3 = totals.get("L3_pass", 0)
    print(r"% Auto-generated by paper/scripts/gen_stats.py — do not edit.")
    print(rf"\newcommand{{\statRawSections}}{{{raw}}}")
    print(rf"\newcommand{{\statEncoded}}{{{enc}}}")
    print(rf"\newcommand{{\statLOnePass}}{{{l1}}}")
    print(rf"\newcommand{{\statLTwoPass}}{{{l2}}}")
    print(rf"\newcommand{{\statLThreePass}}{{{l3}}}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
