"""
Static site generator - produces a browsable HTML site from the statute library.

Generates an index page linking to individual statute pages,
each with English explanation, Mermaid diagram, source code, and metadata.
Designed for deployment to GitHub Pages so law students can browse
modeled statutes without installing anything.
"""

from pathlib import Path
from typing import Optional, List, Dict
import json

import click

from yuho.services.analysis import analyze_file
from yuho.transpile import TranspileTarget, get_transpiler


_SHARED_CSS = """\
*,*::before,*::after{box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;margin:0;padding:0;color:#1a1a2e;background:#fafbfc}
a{color:#2563eb;text-decoration:none}
a:hover{text-decoration:underline}
nav{background:#1a1a2e;color:#fff;padding:.75rem 1.5rem;position:sticky;top:0;z-index:10;display:flex;align-items:center;gap:1rem}
nav .logo{font-weight:700;font-size:1.1rem;letter-spacing:.5px}
nav a{color:#94a3b8}
nav a:hover{color:#fff;text-decoration:none}
.container{max-width:960px;margin:0 auto;padding:1.5rem 1rem}
footer{margin-top:3rem;padding:1rem 0;border-top:1px solid #e2e8f0;font-size:.8rem;color:#94a3b8;text-align:center}"""

_INDEX_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Yuho Statute Library</title>
<style>
{css}
.hero{{background:linear-gradient(135deg,#1a1a2e 0%,#16213e 100%);color:#fff;padding:3rem 1.5rem;text-align:center}}
.hero h1{{margin:0 0 .5rem 0;font-size:2rem}}
.hero p{{margin:0;color:#94a3b8;font-size:1.05rem}}
.search-box{{max-width:480px;margin:1.5rem auto 0;position:relative}}
.search-box input{{width:100%;padding:.75rem 1rem .75rem 2.5rem;border:none;border-radius:8px;font-size:1rem;background:rgba(255,255,255,.12);color:#fff;outline:none}}
.search-box input::placeholder{{color:#64748b}}
.search-box svg{{position:absolute;left:.75rem;top:50%;transform:translateY(-50%);width:16px;height:16px;fill:#64748b}}
.stats{{display:flex;gap:1.5rem;justify-content:center;margin-top:1.5rem}}
.stat{{text-align:center}}
.stat .num{{font-size:1.5rem;font-weight:700}}
.stat .label{{font-size:.8rem;color:#94a3b8}}
.grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:1rem;margin-top:1.5rem}}
.card{{border:1px solid #e2e8f0;border-radius:8px;padding:1.25rem;transition:box-shadow .15s,transform .15s;display:block;color:inherit;background:#fff}}
.card:hover{{box-shadow:0 4px 12px rgba(0,0,0,.08);transform:translateY(-1px);text-decoration:none}}
.card h2{{margin:0 0 .25rem 0;font-size:1rem;color:#1a1a2e}}
.card .section-num{{color:#2563eb;font-weight:600}}
.card .desc{{font-size:.85rem;color:#64748b;margin:.25rem 0 0 0;line-height:1.4}}
.card .tags{{display:flex;gap:.4rem;margin-top:.5rem;flex-wrap:wrap}}
.card .tag{{font-size:.7rem;background:#eff6ff;color:#2563eb;padding:.15rem .5rem;border-radius:99px}}
.empty{{text-align:center;color:#94a3b8;padding:2rem;display:none}}
</style>
</head>
<body>
<nav><span class="logo">Yuho</span><a href="index.html">Library</a></nav>
<div class="hero">
<h1>Singapore Penal Code</h1>
<p>Criminal law statutes modeled as structured, executable code</p>
<div class="search-box">
<svg viewBox="0 0 24 24"><path d="M15.5 14h-.79l-.28-.27A6.47 6.47 0 0016 9.5 6.5 6.5 0 109.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zM9.5 14C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"/></svg>
<input type="text" id="search" placeholder="Search statutes..." autocomplete="off">
</div>
<div class="stats">
<div class="stat"><div class="num">{count}</div><div class="label">Statutes</div></div>
<div class="stat"><div class="num">{category_count}</div><div class="label">Categories</div></div>
</div>
</div>
<div class="container">
<div class="grid" id="grid">{cards}</div>
<div class="empty" id="empty">No statutes match your search.</div>
<footer>Generated by Yuho &middot; Statutes are for educational purposes only</footer>
</div>
<script>
const search=document.getElementById('search'),grid=document.getElementById('grid'),empty=document.getElementById('empty');
search.addEventListener('input',()=>{{
  const q=search.value.toLowerCase();
  let visible=0;
  grid.querySelectorAll('.card').forEach(c=>{{
    const match=c.dataset.search.includes(q);
    c.style.display=match?'':'none';
    if(match)visible++;
  }});
  empty.style.display=visible?'none':'block';
}});
</script>
</body>
</html>"""

_STATUTE_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>s{section} {title} - Yuho</title>
<style>
{css}
.breadcrumb{{font-size:.85rem;color:#64748b;margin-bottom:1rem}}
.breadcrumb a{{color:#2563eb}}
.statute-header{{margin-bottom:1.5rem}}
.statute-header h1{{margin:0 0 .25rem 0;font-size:1.5rem}}
.statute-header .subtitle{{color:#64748b;font-size:.95rem}}
.meta-grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:.75rem;margin:1rem 0}}
.meta-item{{background:#f8fafc;border:1px solid #e2e8f0;border-radius:6px;padding:.6rem .8rem}}
.meta-item .label{{font-size:.7rem;text-transform:uppercase;letter-spacing:.5px;color:#94a3b8;margin-bottom:.15rem}}
.meta-item .value{{font-size:.9rem;color:#1a1a2e}}
.tabs{{display:flex;gap:0;border-bottom:2px solid #e2e8f0;margin:1.5rem 0 0 0}}
.tab{{padding:.6rem 1.2rem;cursor:pointer;font-size:.9rem;color:#64748b;border-bottom:2px solid transparent;margin-bottom:-2px;background:none;border-top:none;border-left:none;border-right:none;font-family:inherit}}
.tab:hover{{color:#1a1a2e}}
.tab.active{{color:#2563eb;border-bottom-color:#2563eb;font-weight:600}}
.tab-content{{display:none;padding:1rem 0}}
.tab-content.active{{display:block}}
pre{{background:#f1f5f9;padding:1rem;border-radius:6px;overflow-x:auto;white-space:pre-wrap;font-size:.85rem;line-height:1.6;border:1px solid #e2e8f0}}
.mermaid{{background:#fff;padding:1rem;border:1px solid #e2e8f0;border-radius:6px;margin:1rem 0;overflow-x:auto}}
.nav-links{{display:flex;justify-content:space-between;margin-top:2rem;padding-top:1rem;border-top:1px solid #e2e8f0}}
.nav-links a{{font-size:.9rem}}
</style>
</head>
<body>
<nav><span class="logo">Yuho</span><a href="index.html">Library</a></nav>
<div class="container">
<div class="breadcrumb"><a href="index.html">Library</a> / Section {section}</div>
<div class="statute-header">
<h1><span style="color:#2563eb">s{section}</span> {title}</h1>
<div class="subtitle">Singapore Penal Code</div>
</div>
{meta_block}
<div class="tabs">
<button class="tab active" onclick="showTab(event,'english')">English Explanation</button>
<button class="tab" onclick="showTab(event,'diagram')">Decision Diagram</button>
<button class="tab" onclick="showTab(event,'source')">Source Code</button>
</div>
<div class="tab-content active" id="english"><pre>{english}</pre></div>
<div class="tab-content" id="diagram"><div class="mermaid">{mermaid}</div></div>
<div class="tab-content" id="source"><pre>{source}</pre></div>
<div class="nav-links">{prev_link}{next_link}</div>
<footer>Generated by Yuho &middot; For educational purposes only</footer>
</div>
<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
<script>
mermaid.initialize({{startOnLoad:false,theme:'default'}});
function showTab(e,id){{
  document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));
  document.querySelectorAll('.tab-content').forEach(t=>t.classList.remove('active'));
  e.target.classList.add('active');
  document.getElementById(id).classList.add('active');
  if(id==='diagram')mermaid.run({{querySelector:'#diagram .mermaid'}});
}}
</script>
</body>
</html>"""


def _esc(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _categorize(name: str) -> str:
    """derive category from directory name for card tags."""
    categories = {
        "murder": "Homicide", "culpable_homicide": "Homicide",
        "punishment_for_murder": "Homicide",
        "hurt": "Bodily Harm", "grievous_hurt": "Bodily Harm",
        "voluntarily_causing": "Bodily Harm",
        "assault": "Bodily Harm", "criminal_force": "Bodily Harm",
        "theft": "Property", "robbery": "Property", "dacoity": "Property",
        "extortion": "Property", "misappropriation": "Property",
        "stolen_property": "Property",
        "cheating": "Fraud", "forgery": "Fraud",
        "breach_of_trust": "Fraud",
        "kidnapping": "Kidnapping",
        "defamation": "Defamation",
    }
    lower = name.lower()
    for key, cat in categories.items():
        if key in lower:
            return cat
    return "General"


def run_static_site(
    *,
    directory: str = "library",
    output_dir: str = "site",
    verbose: bool = False,
) -> None:
    """Generate a static HTML site from the statute library."""
    lib_path = Path(directory)
    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    english_t = get_transpiler(TranspileTarget.ENGLISH)
    mermaid_t = get_transpiler(TranspileTarget.MERMAID)

    statute_files = sorted(lib_path.rglob("statute.yh"))
    cards = []
    pages: List[Dict] = [] # collect for prev/next nav
    generated = 0
    categories = set()

    for yh_file in statute_files:
        result = analyze_file(str(yh_file))
        if not result.is_valid or not result.ast or not result.ast.statutes:
            if verbose:
                click.echo(f"  skip: {yh_file} (parse error)")
            continue

        source_text = yh_file.read_text(encoding="utf-8")
        for statute in result.ast.statutes:
            section = statute.section_number
            title = statute.title.value if statute.title else "Untitled"
            slug = f"s{section}"
            category = _categorize(yh_file.parent.name)
            categories.add(category)

            english = english_t.transpile(result.ast)
            mermaid = mermaid_t.transpile(result.ast)

            meta_lines = []
            if statute.jurisdiction:
                meta_lines.append(("Jurisdiction", str(statute.jurisdiction)))
            if statute.jurisdiction_meta:
                for k, v in statute.jurisdiction_meta.items():
                    meta_lines.append((k.replace("_", " ").title(), str(v)))

            # count elements for metadata
            element_count = 0
            if statute.elements:
                element_count = len(statute.elements)
            exception_count = 0
            if statute.exceptions:
                exception_count = len(statute.exceptions)
            has_penalty = bool(statute.penalty)

            meta_lines.append(("Section", str(section)))
            meta_lines.append(("Category", category))
            if element_count:
                meta_lines.append(("Elements", str(element_count)))
            if exception_count:
                meta_lines.append(("Exceptions", str(exception_count)))
            meta_lines.append(("Penalty", "Yes" if has_penalty else "No"))

            meta_block = ""
            if meta_lines:
                items = "".join(
                    f'<div class="meta-item"><div class="label">{_esc(l)}</div><div class="value">{_esc(v)}</div></div>'
                    for l, v in meta_lines
                )
                meta_block = f'<div class="meta-grid">{items}</div>'

            pages.append({
                "section": section,
                "title": title,
                "slug": slug,
                "category": category,
                "english": english,
                "mermaid": mermaid,
                "source": source_text,
                "meta_block": meta_block,
                "dir_name": yh_file.parent.name,
                "element_count": element_count,
                "exception_count": exception_count,
            })

    # generate statute pages with prev/next navigation
    for i, page in enumerate(pages):
        prev_link = ""
        next_link = ""
        if i > 0:
            p = pages[i - 1]
            prev_link = f'<a href="{p["slug"]}.html">&larr; s{p["section"]} {_esc(p["title"])}</a>'
        if i < len(pages) - 1:
            n = pages[i + 1]
            next_link = f'<a href="{n["slug"]}.html">s{n["section"]} {_esc(n["title"])} &rarr;</a>'

        html = _STATUTE_TEMPLATE.format(
            css=_SHARED_CSS,
            section=page["section"],
            title=_esc(page["title"]),
            english=_esc(page["english"]),
            mermaid=page["mermaid"],
            source=_esc(page["source"]),
            meta_block=page["meta_block"],
            prev_link=prev_link,
            next_link=next_link,
        )
        page_file = out_path / f'{page["slug"]}.html'
        page_file.write_text(html, encoding="utf-8")
        generated += 1

        # build card for index
        desc_parts = []
        if page["element_count"]:
            desc_parts.append(f'{page["element_count"]} elements')
        if page["exception_count"]:
            desc_parts.append(f'{page["exception_count"]} exceptions')
        desc = " &middot; ".join(desc_parts) if desc_parts else page["dir_name"]
        search_text = f's{page["section"]} {page["title"]} {page["category"]} {page["dir_name"]}'.lower()

        cards.append(
            f'<a class="card" href="{page["slug"]}.html" data-search="{_esc(search_text)}">'
            f'<h2><span class="section-num">s{page["section"]}</span> {_esc(page["title"])}</h2>'
            f'<p class="desc">{desc}</p>'
            f'<div class="tags"><span class="tag">{_esc(page["category"])}</span></div></a>'
        )

    index = _INDEX_TEMPLATE.format(
        css=_SHARED_CSS,
        count=generated,
        category_count=len(categories),
        cards="\n".join(cards),
    )
    (out_path / "index.html").write_text(index, encoding="utf-8")
    click.echo(f"Static site generated: {generated} pages -> {out_path}/")
