"""
Static site generator - produces a browsable HTML site from the statute library.

Generates an index page linking to individual statute pages,
each with English explanation, Mermaid diagram, and metadata.
"""

from pathlib import Path
from typing import Optional

import click

from yuho.services.analysis import analyze_file
from yuho.transpile import TranspileTarget, get_transpiler


_INDEX_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Yuho Statute Library</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; color: #222; }}
h1 {{ border-bottom: 2px solid #333; padding-bottom: .5rem; }}
.card {{ border: 1px solid #ddd; border-radius: 8px; padding: 1rem 1.5rem; margin: .75rem 0; text-decoration: none; color: inherit; display: block; transition: box-shadow .15s; }}
.card:hover {{ box-shadow: 0 2px 8px rgba(0,0,0,.1); }}
.card h2 {{ margin: 0 0 .25rem 0; font-size: 1.1rem; color: #1a73e8; }}
.card p {{ margin: 0; font-size: .9rem; color: #666; }}
footer {{ margin-top: 2rem; padding-top: .5rem; border-top: 1px solid #ddd; font-size: .8rem; color: #999; }}
</style>
</head>
<body>
<h1>Yuho Statute Library</h1>
<p>{count} statutes available.</p>
{cards}
<footer>Generated by Yuho static site builder</footer>
</body>
</html>"""

_STATUTE_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Section {section}: {title}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; color: #222; }}
h1 {{ border-bottom: 2px solid #333; padding-bottom: .5rem; }}
h2 {{ color: #444; margin-top: 1.5rem; }}
pre {{ background: #f5f5f5; padding: 1rem; border-radius: 4px; overflow-x: auto; white-space: pre-wrap; font-size: .9rem; }}
.mermaid {{ background: #fff; padding: 1rem; border: 1px solid #ddd; border-radius: 4px; margin: 1rem 0; }}
a.back {{ display: inline-block; margin-bottom: 1rem; color: #1a73e8; text-decoration: none; }}
a.back:hover {{ text-decoration: underline; }}
.meta {{ background: #f9f9f9; padding: .75rem 1rem; border-radius: 4px; font-size: .85rem; color: #555; margin-bottom: 1rem; }}
footer {{ margin-top: 2rem; padding-top: .5rem; border-top: 1px solid #ddd; font-size: .8rem; color: #999; }}
</style>
</head>
<body>
<a class="back" href="index.html">&larr; Back to index</a>
<h1>Section {section}: {title}</h1>
{meta_block}
<h2>English Explanation</h2>
<pre>{english}</pre>
<h2>Decision Diagram</h2>
<div class="mermaid">
{mermaid}
</div>
<h2>Source Code</h2>
<pre>{source}</pre>
<footer>Generated by Yuho static site builder</footer>
<script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
<script>mermaid.initialize({{startOnLoad:true, theme:'default'}});</script>
</body>
</html>"""


def _esc(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def run_static_site(
    *,
    directory: str = "library",
    output_dir: str = "site",
    verbose: bool = False,
) -> None:
    """Generate a static HTML site from the statute library."""
    lib_path = Path(directory)
    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    english_t = get_transpiler(TranspileTarget.ENGLISH)
    mermaid_t = get_transpiler(TranspileTarget.MERMAID)

    statute_files = sorted(lib_path.rglob("statute.yh"))
    cards = []
    generated = 0

    for yh_file in statute_files:
        result = analyze_file(str(yh_file))
        if not result.is_valid or not result.ast or not result.ast.statutes:
            if verbose:
                click.echo(f"  skip: {yh_file} (parse error)")
            continue

        source_text = yh_file.read_text(encoding="utf-8")
        for statute in result.ast.statutes:
            section = statute.section_number
            title = statute.title.value if statute.title else "Untitled"
            slug = f"s{section}"

            english = english_t.transpile(result.ast)
            mermaid = mermaid_t.transpile(result.ast)

            meta_lines = []
            if statute.jurisdiction:
                meta_lines.append(f"Jurisdiction: {statute.jurisdiction}")
            if statute.jurisdiction_meta:
                for k, v in statute.jurisdiction_meta.items():
                    meta_lines.append(f"{k}: {v}")
            meta_block = ""
            if meta_lines:
                meta_block = '<div class="meta">' + "<br>".join(_esc(m) for m in meta_lines) + "</div>"

            page = _STATUTE_TEMPLATE.format(
                section=section,
                title=_esc(title),
                english=_esc(english),
                mermaid=mermaid,
                source=_esc(source_text),
                meta_block=meta_block,
            )
            page_file = out_path / f"{slug}.html"
            page_file.write_text(page, encoding="utf-8")
            generated += 1

            cards.append(
                f'<a class="card" href="{slug}.html">'
                f"<h2>Section {section}: {_esc(title)}</h2>"
                f"<p>{_esc(yh_file.parent.name)}</p></a>"
            )

    index = _INDEX_TEMPLATE.format(count=generated, cards="\n".join(cards))
    (out_path / "index.html").write_text(index, encoding="utf-8")
    click.echo(f"Static site generated: {generated} pages → {out_path}/")
