graph TD

    A[Section 415] --> B[Statute: Cheating] --> C[Definition: Whoever, by deceiving any person, fraudulently or dishonestly induces the person so deceived to deliver any property to any person, or to consent that any person shall retain any property, or intentionally induces the person so deceived to do or omit to do anything which he would not do or omit if he were not so deceived, and which act or omission causes or is likely to cause damage or harm to that person in body, mind, reputation, or property, is said to cheat.]

    C --> D[Result: ofGeneric]
    D --> D1[Imprisonment Duration: 3 years]
    D --> D2[Fine: None]
    D --> D3[Supplementary Punishment: None]

    C --> E[Result: ofPersonation]
    E --> E1[Imprisonment Duration: 7 years]
    E --> E2[Fine: None]
    E --> E3[Supplementary Punishment: A person convicted of cheating by personation shall be disqualified for such period as the court may order from holding any office of profit under the Government or from practicing any profession or carrying on any trade or business.]
