graph TD

    A[Section 383] --> B[Statute: Extortion] --> C[Definition: Whoever intentionally puts any person in fear of any injury to that person or to any other, and thereby dishonestly induces the person so put in fear to deliver to any person any property or valuable security, or anything signed or sealed which may be converted into a valuable security, commits extortion.]

    C --> D[Result: ofGeneric]
    D --> D1[Imprisonment Duration: 3 year]
    D --> D2[Fine: None]
    D --> D3[Supplementary Punishment: None]

    C --> E[Result: withThreatToCauseDeath]
    E --> E1[Imprisonment Duration: 10 year]
    E --> E2[Fine: None]
    E --> E3[Supplementary Punishment: None]

    C --> F[Result: withThreatToCauseGrievousHurt]
    F --> F1[Imprisonment Duration: 7 year]
    F --> F2[Fine: None]
    F --> F3[Supplementary Punishment: None]
