graph TD

    A[Section 300] --> B[Statute: Murder] --> C[Definition: Whoever causes death by doing an act with the intention of causing death, or with the intention of causing such bodily injury as is likely to cause death, or with the knowledge that he is likely by such act to cause death, commits the offence of murder.]

    C --> D[Result: ofGeneric]
    D --> D1[Imprisonment Duration: Life imprisonment]
    D --> D2[Fine: None]
    D --> D3[Supplementary Punishment: None]

    C --> E[Result: ofMurderWithDeathSentence]
    E --> E1[Imprisonment Duration: None]
    E --> E2[Fine: None]
    E --> E3[Supplementary Punishment: Death penalty]
