graph TD

    A[Section 378] --> B[Statute: Theft] --> C[Definition: Whoever, intending to take dishonestly any movable property out of the possession of any person without that person’s consent, moves that property in order to such taking, is said to commit theft.]

    C --> D[Result: ofGeneric]
    D --> D1[Imprisonment Duration: 3 years]
    D --> D2[Fine: None]
    D --> D3[Supplementary Punishment: None]

    C --> E[Result: ofMotorVehicle]
    E --> E1[Imprisonment Duration: 7 years]
    E --> E2[Fine: None]
    E --> E3[Supplementary Punishment: A person convicted of an offence under this section shall, unless the court for special reasons thinks fit to order otherwise, be disqualified for such period as the court may order from the date of his release from imprisonment from holding or obtaining a driving licence under the Road Traffic Act 1961.]

    C --> F[Result: ofDwellingHouse]
    F --> F1[Imprisonment Duration: 7 years]
    F --> F2[Fine: None]
    F --> F3[Supplementary Punishment: None]

    C --> G[Result: ofClerkOrServant]
    G --> G1[Imprisonment Duration: 7 years]
    G --> G2[Fine: None]
    G --> G3[Supplementary Punishment: None]

    C --> H[Result: afterPreparationCausingDeath]
    H --> H1[Imprisonment Duration: 10 years]
    H --> H2[Fine: None]
    H --> H3[Supplementary Punishment: Caning with not less than 3 strokes]
