graph TD

    A[Section 441] --> B[Statute: Criminal Trespass] --> C[Definition: Whoever enters into or upon property in the possession of another with intent to commit an offence or to intimidate, insult or annoy any person in possession of such property, or having lawfully entered into or upon such property, unlawfully remains there with intent thereby to intimidate, insult or annoy any such person, or with intent to commit an offence, is said to commit 'criminal trespass.']

    C --> D[Result: ofGeneric]
    D --> D1[Imprisonment Duration: 3 months]
    D --> D2[Fine: None]
    D --> D3[Supplementary Punishment: None]

    C --> E[Result: ofHouseTrespass]
    E --> E1[Imprisonment Duration: 1 year]
    E --> E2[Fine: None]
    E --> E3[Supplementary Punishment: None]
