"""
HTML transpiler - produces standalone HTML with embedded Mermaid diagrams.

Combines English transpiler output with Mermaid diagrams into a single
self-contained HTML page that renders in any modern browser.
"""

from typing import List

from yuho.ast import nodes
from yuho.transpile.base import TranspileTarget, TranspilerBase
from yuho.transpile.english_transpiler import EnglishTranspiler
from yuho.transpile.mermaid_transpiler import MermaidTranspiler


_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
body {{ font-family: 'Georgia', serif; max-width: 960px; margin: 2rem auto; padding: 0 1rem; color: #222; }}
h1 {{ border-bottom: 2px solid #333; padding-bottom: .5rem; }}
h2 {{ color: #444; margin-top: 2rem; }}
pre {{ background: #f5f5f5; padding: 1rem; border-radius: 4px; overflow-x: auto; white-space: pre-wrap; }}
.mermaid {{ background: #fff; padding: 1rem; border: 1px solid #ddd; border-radius: 4px; margin: 1rem 0; }}
footer {{ margin-top: 3rem; border-top: 1px solid #ccc; padding-top: .5rem; font-size: .85rem; color: #888; }}
</style>
</head>
<body>
<h1>{title}</h1>
<h2>English Explanation</h2>
<pre>{english}</pre>
<h2>Decision Diagram</h2>
<div class="mermaid">
{mermaid}
</div>
<footer>Generated by Yuho</footer>
<script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
<script>mermaid.initialize({{startOnLoad:true, theme:'default'}});</script>
</body>
</html>"""


class HTMLTranspiler(TranspilerBase):
    """Transpile Yuho AST to standalone HTML with embedded Mermaid."""

    @property
    def target(self) -> TranspileTarget:
        return TranspileTarget.HTML

    def transpile(self, ast: nodes.ModuleNode) -> str:
        english_t = EnglishTranspiler()
        mermaid_t = MermaidTranspiler()
        english_text = english_t.transpile(ast)
        mermaid_text = mermaid_t.transpile(ast)
        title = "Yuho Statute"
        if ast.statutes:
            s = ast.statutes[0]
            title = f"Section {s.section_number}"
            if s.title:
                title += f": {s.title.value}"
        english_escaped = english_text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        return _HTML_TEMPLATE.format(
            title=title,
            english=english_escaped,
            mermaid=mermaid_text,
        )
