#lang racket

(define-type Token
    [comment (string)]
    [multiline-comment (string)]
    [true]
    [false]
    [match]
    [case]
    [consequence]
    [pass]
    [struct]
    [fn]
    [percent]
    [money-prefix]
    [identifier (string)]
    [dot]
    [string (string)]
    [integer (integer)]
    [float (float)]
    [percentage (integer)]
    [money (string)]
    [date (string)]
    [duration (string)]
    [plus]
    [minus]
    [mult]
    [div]
    [assign]
    [equal]
    [notequal]
    [gt]
    [lt]
    [and]
    [or]
    [semicolon]
    [colon]
    [lbrace]
    [rbrace]
    [lparen]
    [rparen]
    [comma]
    [underscore]
    [whitespace])