#!/usr/bin/env python3
"""Generate ``docs/user/cli-reference.md`` from Click's command tree.

Walks ``yuho.cli.main.cli`` recursively and emits a Markdown doc that
cannot drift from the actual implementation. Run after every CLI change
to keep the doc in lockstep.

Usage:
    python3 scripts/gen_cli_reference.py
    python3 scripts/gen_cli_reference.py --check          # CI mode: fail if doc would change
    python3 scripts/gen_cli_reference.py --stdout         # print, don't write
"""

from __future__ import annotations

import argparse
import datetime as _dt
import io
import sys
from pathlib import Path
from typing import List, Optional

import click

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "docs" / "user" / "cli-reference.md"


def _format_command_help(name: str, cmd: click.Command, ctx: click.Context, depth: int = 0) -> str:
    """Capture the formatted help text Click would print for one command."""
    formatter = click.HelpFormatter(width=80, max_width=80)
    cmd.format_help(ctx, formatter)
    return formatter.getvalue().rstrip()


def _emit_command(buf: io.StringIO, path: List[str], cmd: click.Command, parent_ctx: Optional[click.Context]) -> None:
    """Recursively emit Markdown for a command and any subcommands."""
    name = path[-1]
    full = " ".join(path)
    short_help = (cmd.get_short_help_str(limit=120) or "").strip() or "(no description)"

    heading_level = "##" if len(path) == 1 else "###"
    buf.write(f"{heading_level} `{full}`\n\n")
    buf.write(f"{short_help}\n\n")

    # Build a child context so subcommand help is invokable.
    ctx = click.Context(cmd, info_name=name, parent=parent_ctx)

    # Capture the canonical Click help block.
    formatter = click.HelpFormatter(width=88, max_width=88)
    cmd.format_help(ctx, formatter)
    help_text = formatter.getvalue().rstrip()

    buf.write("```\n")
    buf.write(help_text + "\n")
    buf.write("```\n\n")

    # Recurse into subcommands (only Group has them).
    if isinstance(cmd, click.Group):
        for sub_name in sorted(cmd.commands):
            sub_cmd = cmd.commands[sub_name]
            _emit_command(buf, path + [sub_name], sub_cmd, ctx)


def _emit_summary_table(buf: io.StringIO, cli: click.Group) -> None:
    """One-line-per-command summary table at the top of the doc."""
    buf.write("## Command summary\n\n")
    buf.write("| Command | Description |\n|---|---|\n")
    for name in sorted(cli.commands):
        cmd = cli.commands[name]
        short = (cmd.get_short_help_str(limit=120) or "").strip() or "—"
        # Escape pipes in short help for Markdown table.
        short = short.replace("|", "\\|")
        buf.write(f"| `yuho {name}` | {short} |\n")
    buf.write("\n")


def render() -> str:
    from yuho.cli.main import cli

    buf = io.StringIO()
    today = _dt.date.today().isoformat()

    buf.write("# Yuho CLI reference\n\n")
    buf.write(
        f"_Auto-generated by `scripts/gen_cli_reference.py` on {today}._\n"
        "_Do not edit by hand — regenerate after every CLI change._\n\n"
    )
    buf.write(
        "This document mirrors the output of `yuho <subcommand> --help` for "
        "every implemented CLI command. The generator walks Click's command "
        "tree directly, so the doc and the binary cannot disagree.\n\n"
    )

    _emit_summary_table(buf, cli)

    buf.write("---\n\n## Per-command details\n\n")

    for name in sorted(cli.commands):
        sub_cmd = cli.commands[name]
        _emit_command(buf, [f"yuho {name}"], sub_cmd, None)

    buf.write("---\n\n## Global options\n\n")
    formatter = click.HelpFormatter(width=88, max_width=88)
    ctx = click.Context(cli, info_name="yuho")
    cli.format_help(ctx, formatter)
    buf.write("```\n" + formatter.getvalue().rstrip() + "\n```\n")

    return buf.getvalue()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument("--check", action="store_true", help="Exit non-zero if doc would change")
    parser.add_argument("--stdout", action="store_true", help="Print to stdout instead of writing")
    args = parser.parse_args()

    new = render()

    if args.stdout:
        sys.stdout.write(new)
        return 0

    if args.check:
        if not OUT.exists():
            print(f"error: {OUT} does not exist (run without --check to create)", file=sys.stderr)
            return 1
        old = OUT.read_text(encoding="utf-8")
        if old != new:
            print(f"error: {OUT} is out of date. Run `python3 scripts/gen_cli_reference.py` to regenerate.", file=sys.stderr)
            return 2
        print(f"OK: {OUT.relative_to(REPO)} matches CLI tree.", file=sys.stderr)
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(new, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({len(new)} bytes)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
