#!/usr/bin/env python3
"""Emit reproducible SLOC + corpus statistics for the paper.

Output: ``paper/stats-extra.tex`` with a set of ``\newcommand`` definitions
that the implementation §4 SLOC table and other paper sections can use.

Run alongside ``paper/scripts/gen_stats.py`` (which emits coverage-
related stats); this script emits source-tree-level counts.

Usage:
    python3 scripts/repo_stats.py                 # write paper/stats-extra.tex
    python3 scripts/repo_stats.py --json          # emit JSON instead
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Tuple

REPO = Path(__file__).resolve().parent.parent

# Layer name -> list of paths (files or dirs) and matching glob patterns.
LAYERS: List[Tuple[str, List[str], List[str]]] = [
    ("Tree-sitter grammar",  ["src/tree-sitter-yuho/grammar.js"], []),
    ("AST",                  ["src/yuho/ast"],                    ["*.py"]),
    ("Parser wrapper",       ["src/yuho/parser"],                 ["*.py"]),
    ("Transpilers",          ["src/yuho/transpile"],              ["*.py"]),
    ("Verification",         ["src/yuho/verify"],                 ["*.py"]),
    ("CLI",                  ["src/yuho/cli"],                    ["*.py"]),
    ("Language Server",      ["src/yuho/lsp"],                    ["*.py"]),
    ("MCP server",           ["src/yuho/mcp"],                    ["*.py"]),
    ("Library helpers",      ["src/yuho/library", "src/yuho/services"], ["*.py"]),
    ("Phase-D / scripts",    ["scripts"],                         ["*.py"]),
    ("Tests",                ["tests"],                           ["*.py"]),
    ("Encoded library .yh",  ["library/penal_code"],              ["*.yh"]),
    ("Paper prose",          ["paper/sections"],                  ["*.tex"]),
    ("VS Code extension",    ["editors/vscode-yuho/src"],         ["*.ts"]),
    ("Browser extension",    ["editors/browser-yuho/src"],        ["*.js", "*.css"]),
    ("Explorer site",        ["editors/explorer-site"],           ["*.py"]),
    ("Benchmarks",           ["benchmarks"],                      ["*.py"]),
    ("Simulator",            ["simulator"],                       ["*.py", "*.yaml"]),
]


def _count_lines(paths: List[str], patterns: List[str]) -> int:
    total = 0
    for p in paths:
        full = REPO / p
        if not full.exists():
            continue
        if full.is_file():
            total += sum(1 for _ in full.read_text(errors="ignore").splitlines())
            continue
        for pat in patterns or ["*"]:
            for f in full.rglob(pat):
                if "__pycache__" in f.parts:
                    continue
                if f.is_file():
                    try:
                        total += sum(1 for _ in f.read_text(errors="ignore").splitlines())
                    except Exception:
                        pass
    return total


def _git_head() -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True, text=True, cwd=REPO, timeout=5,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass
    return ""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument("--json", dest="json_output", action="store_true",
                        help="Emit JSON instead of LaTeX newcommand stats")
    args = parser.parse_args()

    stats: Dict[str, int] = {}
    for layer, paths, patterns in LAYERS:
        stats[layer] = _count_lines(paths, patterns)

    total = sum(v for k, v in stats.items() if k != "Encoded library .yh")
    library = stats.get("Encoded library .yh", 0)

    if args.json_output:
        print(json.dumps({
            "git_head": _git_head(),
            "layers": stats,
            "totals": {"implementation": total, "library_yh": library},
        }, indent=2))
        return 0

    # LaTeX output: one \newcommand per layer (sanitised name) + totals.
    out_lines = [
        "% Auto-generated by scripts/repo_stats.py — do not edit.",
        f"% git HEAD: {_git_head()}",
    ]
    for layer, val in stats.items():
        cmd = "stat" + "".join(c.title() if c.isalnum() else "" for c in layer.replace(".yh", "Yh"))
        out_lines.append(f"\\newcommand{{\\{cmd}}}{{{val}}}")
    out_lines.append(f"\\newcommand{{\\statTotalImplementation}}{{{total}}}")
    out_lines.append(f"\\newcommand{{\\statTotalLibrary}}{{{library}}}")

    out_path = REPO / "paper" / "stats-extra.tex"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(out_lines) + "\n", encoding="utf-8")
    print(f"wrote {out_path.relative_to(REPO)}", file=sys.stderr)
    print("\n".join(out_lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
