import Yuho.CoreYuho.Theorems

#check Yuho.CoreYuho.andStatus_comm
#check Yuho.CoreYuho.orStatus_comm
#check Yuho.CoreYuho.andStatus_assoc
#check Yuho.CoreYuho.orStatus_assoc
#check Yuho.CoreYuho.andStatus_idempotent
#check Yuho.CoreYuho.orStatus_idempotent
#check Yuho.CoreYuho.allStatus_empty
#check Yuho.CoreYuho.anyStatus_empty
#check Yuho.CoreYuho.allStatus_deterministic
#check Yuho.CoreYuho.anyStatus_deterministic
#check Yuho.CoreYuho.allStatus_total
#check Yuho.CoreYuho.anyStatus_total
#check Yuho.CoreYuho.allStatus_notSatisfied_domination
#check Yuho.CoreYuho.anyStatus_satisfied_domination
#check Yuho.CoreYuho.allStatus_unresolved_exact
#check Yuho.CoreYuho.anyStatus_unresolved_exact
#check Yuho.CoreYuho.allStatus_permutation_invariant
#check Yuho.CoreYuho.anyStatus_permutation_invariant
#check Yuho.CoreYuho.requirement_evaluation_deterministic
#check Yuho.CoreYuho.requirement_evaluator_total
#check Yuho.CoreYuho.requirement_lookup_stability
#check Yuho.CoreYuho.requirement_dependency_locality
#check Yuho.CoreYuho.finite_definition_evaluator_total
#check Yuho.CoreYuho.finite_definition_evaluation_deterministic
#check Yuho.CoreYuho.independent_definition_order_invariant
#check Yuho.CoreYuho.exception_defeat_table
#check Yuho.CoreYuho.exception_instance_isolation
#check Yuho.CoreYuho.candidate_branch_exception_isolation
#check Yuho.CoreYuho.nonselected_branch_cannot_transfer
#check Yuho.CoreYuho.presumption_result_total
#check Yuho.CoreYuho.presumption_state_exactly_one
#check Yuho.CoreYuho.presumption_separate_from_offence
#check Yuho.CoreYuho.allegation_equals_independent_evaluation
#check Yuho.CoreYuho.allegation_private_input_isolation
#check Yuho.CoreYuho.case_reordering_preserves_results
#check Yuho.CoreYuho.case_has_no_aggregate_status
#check Yuho.CoreYuho.temporal_success_unique
#check Yuho.CoreYuho.temporal_unique_selection_from_nonoverlap
#check Yuho.CoreYuho.temporal_boundary_half_open
#check Yuho.CoreYuho.temporal_upper_boundary_excluded
#check Yuho.CoreYuho.temporal_version_metadata_irrelevant
#check Yuho.CoreYuho.temporal_gap_has_no_success
#check Yuho.CoreYuho.temporal_overlap_has_no_success
