name:                 yuho-foundation
version:              1.0.0.0
visibility:           public
id:                   yuho-foundation-1.0.0.0-inplace
key:                  yuho-foundation-1.0.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:
    Yuho.CLI Yuho.Core.Source Yuho.Core.Types Yuho.CoreYuho.Conformance
    Yuho.CoreYuho.Normalize Yuho.CoreYuho.Registry
    Yuho.CoreYuho.Semantics Yuho.CoreYuho.TypedFinite
    Yuho.CoreYuho.Types Yuho.Corpus Yuho.Diagram.Build
    Yuho.Diagram.Encode Yuho.Diagram.Types Yuho.Exception.Decode
    Yuho.Exception.Encode Yuho.Exception.Evaluate Yuho.Exception.Run
    Yuho.Exception.Types Yuho.Exception.Validate Yuho.Kernel.Evaluate
    Yuho.Kernel.Run Yuho.Kernel.Validate Yuho.ModelBundle.ChangeSet
    Yuho.ModelBundle.Diff Yuho.ModelBundle.Json
    Yuho.ModelBundle.Package Yuho.ModelBundle.Review
    Yuho.ModelBundle.Run Yuho.ModelBundle.Types
    Yuho.ModelBundle.Validate Yuho.PenaltySelection.Decode
    Yuho.PenaltySelection.Encode Yuho.PenaltySelection.Run
    Yuho.PenaltySelection.Select Yuho.PenaltySelection.Types
    Yuho.PenaltySelection.Validate Yuho.PenaltyTerms.Decode
    Yuho.PenaltyTerms.Encode Yuho.PenaltyTerms.Run
    Yuho.PenaltyTerms.Types Yuho.PenaltyTerms.Validate
    Yuho.Presumption.Decode Yuho.Presumption.Encode
    Yuho.Presumption.Evaluate Yuho.Presumption.Resolve
    Yuho.Presumption.Run Yuho.Presumption.Types
    Yuho.Presumption.Validate Yuho.Protocol.Decode Yuho.Protocol.Encode
    Yuho.Protocol.Json Yuho.Release Yuho.SuppliedProofStatus.Decode
    Yuho.SuppliedProofStatus.Encode Yuho.SuppliedProofStatus.Evaluate
    Yuho.SuppliedProofStatus.Run Yuho.SuppliedProofStatus.Select
    Yuho.SuppliedProofStatus.Types Yuho.SuppliedProofStatus.Validate
    Yuho.Surface.AST Yuho.Surface.Abetment Yuho.Surface.ActorExceptions
    Yuho.Surface.Case Yuho.Surface.CaseFacts Yuho.Surface.Check
    Yuho.Surface.Compile Yuho.Surface.Definitions Yuho.Surface.Explain
    Yuho.Surface.Lexer Yuho.Surface.Lower Yuho.Surface.Modules
    Yuho.Surface.Parser Yuho.Surface.Participation
    Yuho.Surface.Presumption Yuho.Surface.Resolve Yuho.Surface.Temporal
    Yuho.Surface.Token Yuho.Surface.TypedFinite Yuho.TypedFacts.Decode
    Yuho.TypedFacts.Encode Yuho.TypedFacts.Run Yuho.TypedFacts.Types
    Yuho.TypedFacts.Validate Yuho.TypedFiniteRules.Run

import-dirs:
    /home/gongahkia/Desktop/coding/projects/yuho/rewrite/haskell/dist-newstyle/build/x86_64-linux/ghc-9.8.4/yuho-foundation-1.0.0.0/build

library-dirs:
    /home/gongahkia/Desktop/coding/projects/yuho/rewrite/haskell/dist-newstyle/build/x86_64-linux/ghc-9.8.4/yuho-foundation-1.0.0.0/build

library-dirs-static:
    /home/gongahkia/Desktop/coding/projects/yuho/rewrite/haskell/dist-newstyle/build/x86_64-linux/ghc-9.8.4/yuho-foundation-1.0.0.0/build

dynamic-library-dirs:
    /home/gongahkia/Desktop/coding/projects/yuho/rewrite/haskell/dist-newstyle/build/x86_64-linux/ghc-9.8.4/yuho-foundation-1.0.0.0/build

data-dir:
    /home/gongahkia/Desktop/coding/projects/yuho/rewrite/haskell/.

hs-libraries:         HSyuho-foundation-1.0.0.0-inplace
depends:
    aeson-2.3.1.0-5e0237324e38329101f36ee880eef078d7c8f5a7bad57cabc72890c5a6aa0190
    base-4.19.2.0-2a19 bytestring-0.12.1.0-271a containers-0.6.8-f7a9
    crypton-1.1.5-60b5e2213136a047ad2a8706ec895b8b39eabb0b128267ccb28549d874e3a5c5
    directory-1.3.8.5-7915 filepath-1.4.301.0-c6a7 text-2.1.1-e1c6
    time-1.12.2-c57a unix-2.8.6.0-5180

haddock-interfaces:
    /home/gongahkia/Desktop/coding/projects/yuho/rewrite/haskell/dist-newstyle/build/x86_64-linux/ghc-9.8.4/yuho-foundation-1.0.0.0/doc/html/yuho-foundation/yuho-foundation.haddock

haddock-html:
    /home/gongahkia/Desktop/coding/projects/yuho/rewrite/haskell/dist-newstyle/build/x86_64-linux/ghc-9.8.4/yuho-foundation-1.0.0.0/doc/html/yuho-foundation
