apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-yuho
  labels:
    app: yuho
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: yuho
  template:
    metadata:
      labels:
        app: yuho
    spec:
      containers:
        - name: yuho
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: YUHO_LOG_LEVEL
              value: {{ .Values.config.logLevel }}
            - name: YUHO_API_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-yuho-secret
                  key: auth-token
                  optional: true
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /root/.config/yuho
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-yuho-config
